[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sealagrangiax"
authors = [
    { name = "Vadim Bertrand", email = "vadim.bertrand@univ-grenoble-alpes.fr" },
    { name = "Emmanuel Cosme", email = "emmanuel.cosme@univ-grenoble-alpes.fr" },
    { name = "Adeline Leclercq Samson", email = "adeline.leclercq-samson@univ-grenoble-alpes.fr" },
    { name = "Julien Le Sommer", email = "julien.lesommer@univ-grenoble-alpes.fr" },
]

description = "Stochastic and differentiable simulators for ocean surface drifting objects trajectories"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["stochastic", "lagrangian", "trajectory", "sampler", "simulator", "ocean", "sea", "drift", "diffrentiable", "jax"]
license = {text = "Apache-2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

dynamic = ["version", "dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {attr = "sealagrangiax.version.__version__"}

[project.urls]
"Homepage" = "https://github.com/vadmbertr/sealagrangiax"
"Bug Tracker" = "https://github.com/vadmbertr/sealagrangiax/issues"

[tool.setuptools.packages]
find = {}
